# Generated by Django 2.2 on 2020-05-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200514_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='notice',
            field=models.CharField(max_length=300, verbose_name='课程公告'),
        ),
    ]
