# Generated by Django 2.2 on 2020-04-29 14:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('cname', models.CharField(max_length=20, verbose_name='城市名称')),
                ('desc', models.CharField(max_length=300, verbose_name='城市描述')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('org_name', models.CharField(max_length=20, verbose_name='机构名称')),
                ('org_label', models.CharField(max_length=30, verbose_name='机构标签')),
                ('org_type', models.CharField(choices=[('pxjg', '培训机构'), ('gr', '个人'), ('gx', '高校')], max_length=4, verbose_name='机构类别')),
                ('org_click', models.IntegerField(default=0, verbose_name='点击数')),
                ('org_collect', models.IntegerField(default=0, verbose_name='收藏数')),
                ('org_image', models.ImageField(upload_to='org/%Y/%m', verbose_name='logo')),
                ('org_location', models.CharField(max_length=300, verbose_name='机构地址')),
                ('org_learners', models.IntegerField(default=0, verbose_name='学习人数')),
                ('org_courses', models.IntegerField(default=0, verbose_name='课程数')),
                ('org_isauth', models.BooleanField(default=False, verbose_name='是否认证')),
                ('org_ismedal', models.BooleanField(default=False, verbose_name='是否金牌')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.City', verbose_name='所在城市')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('tea_name', models.CharField(max_length=10, verbose_name='教师名')),
                ('tea_workyears', models.FloatField(verbose_name='工作年限')),
                ('tea_company', models.CharField(max_length=20, verbose_name='就职公司')),
                ('tea_position', models.CharField(max_length=20, verbose_name='公司职位')),
                ('tea_features', models.CharField(max_length=100, verbose_name='教学特点')),
                ('tea_click', models.IntegerField(default=0, verbose_name='点击数')),
                ('tea_collect', models.IntegerField(default=0, verbose_name='收藏数')),
                ('tea_age', models.IntegerField(default=20, verbose_name='年龄')),
                ('tea_image', models.ImageField(upload_to='teacher/%Y/%m', verbose_name='头像')),
                ('tea_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='所属机构')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
