# Generated by Django 2.2 on 2020-04-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市信息', 'verbose_name_plural': '城市信息'},
        ),
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': '机构信息', 'verbose_name_plural': '机构信息'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '老师信息', 'verbose_name_plural': '老师信息'},
        ),
    ]
